apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Monitoring stack resources
resources:
  - helmrepo.yaml
  - monitoring-stack.yaml
  - grafana-ingress.yaml
  - grafana-middleware.yaml
  - dashboards/chaos-dashboard.yaml
